# Generated by Django 4.0.1 on 2022-03-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.BooleanField(null=True),
        ),
    ]
